### ISSUE TITLE
Make repost threshold configurable.

### ISSUE THREAD

**Issue by mxie** [thoughtbot/beggar#124]
Probably via ENV var.

**Comment by drapergeek** [comment]
ENV makes sense to me :+1:

**Comment by joeunrue** [comment]
Hi, this actually breaks on Heroku with this error:

```
config var "REPOST_THRESHOLD" must be a string or object
```

**Comment by jeroenvisser101** [comment]
@joeunrue I'm experiencing the same

![](https://www.dropbox.com/s/ooa11n7w5skpzhx/Screenshot%202015-12-21%2012.12.11.png?dl=1)

**Comment by mxie** [comment]
Closing since #125 has been merged, but also #128 for the `app.json` issue. Thanks @joeunrue for the PR!

**Comment by joeunrue** [comment]
Thanks for putting in the hard work!
